
services:
  postgresdb:
    platform: linux/arm64
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: on-failure
    image: accommodation-booking-service
    build: .
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://postgresdb:${POSTGRES_DOCKER_PORT}/${DB_NAME}?createDatabaseIfNotExist=true",
        "spring.datasource.username": "${DB_USERNAME}",
        "spring.datasource.password": "${DB_PASSWORD}",
        "spring.datasource.driver-class-name": "org.postgresql.Driver",
        "spring.jpa.database-platform": "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto": "validate",
        "spring.jpa.show-sql": true,
        "spring.jpa.open-in-view": false,
        "spring.liquibase.change-log": "classpath:/db/changelog/db.changelog-master.yaml"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"

volumes:
  postgres-data:
